###
### A sample margin initialization file.
###

[ global ]
margin name:            Test
vertical resolution:    .05
x resolution:           100000
y resolution:           100
bathymetry file:        test.bathy
sediment file:          test.sediment

###
### Epoch parameters.
###

[ epoch ]
epoch number:           1
epoch duration:         125000y
epoch time step:        100y
epoch process file:     test.epoch

